name: Windows Release Build

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v2.1
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
        working-directory: x360_tools_flutter

      - name: Build Windows
        run: flutter build windows --release
        working-directory: x360_tools_flutter

      - name: Compile Inno Setup Installer
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" windows_installer.iss
        shell: cmd
        working-directory: x360_tools_flutter

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: x360-Tools-Windows-Installer
          path: Output/x360_Tools_v2.0_Setup.exe
